### ISSUE TITLE
Extra Columns test fail

### ISSUE THREAD

**Issue by brianray** [brianray/mm#10]
@hodgesds
# 
## ERROR: test_extra_columns (test_extra_columns.TestColumns)

Traceback (most recent call last):
  File "/Users/bray/mm/tests/test_extra_columns.py", line 36, in test_extra_columns
    self.check("test_extra_columns.xls", my_data)
  File "/Users/bray/mm/tests/test_extra_columns.py", line 45, in check
    cell_type = xls.get_type(row, col)
    return self.cell_types[str(worksheet.cell_type(row, colm))]
  File "/Users/bray/mm/mm_env/lib/python2.7/site-packages/xlrd/sheet.py", line 418, in cell_type
    return self._cell_types[rowx][colx]
IndexError: array index out of range
-------------------- >> begin captured logging << --------------------

**Comment by brianray** [comment]
@hodgesds I lied, that was my test that failed.
