### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by SachaMPS** [brianray/mm#11]
There was already a ticket regarding this issue... It only occurs if I export 2 or more rows at once...

You can find the model here: 
https://gist.github.com/SachaMPS/e8448ffede30ed4f204c

Heres the traceback:

ERROR:django.request:Internal Server Error: /admin/contact/orderitem/
Traceback (most recent call last):
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 366, in wrapper
    return self.admin_site.admin_view(view)(_args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 196, in inner
    return view(request, _args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1153, in changelist_view
    response = self.response_action(request, queryset=cl.get_query_set(request))
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 908, in response_action
    response = func(self, request, queryset)
  File "/Users/sto/Sites/python.dev/python/stw_project/project/apps/contact/admin.py", line 63, in export_as_xls
    data = xlsDoc.writestr()
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/document_writers.py", line 21, in writestr
    return self.composer.run(child=child)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/composer_xls.py", line 220, in run
    self.iterate_grid()
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/composer_base.py", line 26, in iterate_grid
    self.write_cell(self.row_id, self.col_id, cell)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/composer_xls.py", line 165, in write_cell
    self.done_write_cell(row_id, col_id, cell, value, style)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/composer_xls.py", line 176, in done_write_cell
    new_width = get_string_width_from_style(value, style)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/composer_xls.py", line 19, in get_string_width_from_style
    return int(get_string_width(font_name, point_size, char_string) \* 50)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/lib/font_data/decorators.py", line 21, in __call__
    value = self.func(*args)
  File "/Users/sto/Sites/python.dev/python/stw_project/env/lib/python2.7/site-packages/mm/lib/font_data/core.py", line 49, in get_string_width
    str_length = len(char_string)
TypeError: object of type 'int' has no len()

**Comment by SachaMPS** [comment]
Thank you!
