### ISSUE TITLE
Can it support python 3?

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [brianray/mm#29]
It looks not support python3.

 >$ pip install marmir                                                                              
>Collecting marmir
>  Using cached https://files.pythonhosted.org/packages/e4/7d/75d7c821c2a9439ccaad6f70d5cfb8ba3a7d5795b9632f3a9b89a3a40e2e/Marmir-0.1.3.tar.gz
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "/private/var/folders/n3/hnw9vdn51qzf29grjgmcyr800000gn/T/pip-install-8fun0y3l/marmir/setup.py", line 3, in <module>
>        import mm
>      File "/private/var/folders/n3/hnw9vdn51qzf29grjgmcyr800000gn/T/pip-install-8fun0y3l/marmir/mm/__init__.py", line 10, in <module>
>        from document_base import *
>    ModuleNotFoundError: No module named 'document_base'

**Comment by brianray** [comment]
It's a good idea. I'll take a look at it but might need a week or so.

**Comment by minzhou1003** [comment]
I got the same error, any solutions?

**Comment by EOSIT** [comment]
Any updates in the last 2 months?

**Comment by brianray** [comment]
We have started work on this
https://github.com/brianray/mm/tree/python3

**Comment by brianray** [comment]
Try this: https://github.com/brianray/mm/releases/tag/mm3

When us use import mm3 <- with a 3 

Let me know if you find any issues, just create an issue here: https://github.com/brianray/mm/issues/

**Comment by MaJuanWH** [comment]
I got the same error, any solutions?

**Comment by brianray** [comment]
Same error with branch?

https://github.com/brianray/mm/tree/python3

**Comment by MaJuanWH** [comment]
yes

**Comment by MaJuanWH** [comment]
C:\Apython\Anaconda\Lib\site-packages\mm-mm3>python setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import mm
  File "C:\Apython\Anaconda\Lib\site-packages\mm-mm3\mm\__init__.py", line 9, in
 <module>
    from document_base import *
ModuleNotFoundError: No module named 'document_base'

still this error

**Comment by hustjiangtao** [comment]
Default import in py3 is different from py2
