### ISSUE TITLE
gdata_tests.py fails on Win 7, Python 2.7.2

### ISSUE THREAD

**Issue by tathagata** [brianray/mm#4]
```
C:\Users\Tathagata\Documents\GitHub\mm\tests>python gdata_tests.py
Google Username: C-3PO
Google password:
No handlers could be found for logger "mm.composer_xls"
E
======================================================================
ERROR: test_minimal (__main__.TestGdataSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
 File "gdata_tests.py", line 45, in test_minimal
password)
 File "C:\Python27\lib\site-packages\marmir-0.1.1-py2.7.egg\mm\document_writers.py", line 60, in write_gdata
entry = gd_client.Upload(ms, name)
 File "C:\Python27\lib\site-packages\gdata\docs\service.py", line 306, in Upload
folder_or_uri)
 File "C:\Python27\lib\site-packages\gdata\docs\service.py", line 161, in _UploadFile
converter=gdata.docs.DocumentListEntryFromString)
 File "C:\Python27\lib\site-packages\gdata\service.py", line 1236, in Post
media_source=media_source, converter=converter)
 File "C:\Python27\lib\site-packages\gdata\service.py", line 1358, in PostOrPut
'reason': server_response.reason, 'body': result_body}
RequestError: {'status': 400, 'body': 'The spreadsheet you are trying to upload is invalid.', 'reason': 'Bad Request'}

----------------------------------------------------------------------
Ran 1 test in 11.664s

FAILED (errors=1)
```

Printing the values of the dict in the doc in line 36 

```
    mm_doc = mm.Document(my_data)
    print mm_doc.__dict__.values()

 [<mm.grid_base.GridBase object at 0x0236BB50>, <mm.config_base.ConfigBase object at 0x0236BAD0>, <class 'mm.model_base.DataModel'>, [{'msg': 'My first Cell', 'when': datetime.datetime(2013, 2, 18, 19, 35, 11), 'id': 1}, {'msg': 'My second Cell', 'when': datetime.datetime(2013, 2, 18, 19, 35, 11), 'id': 2}], <mm.model_base.DataModel object at 0x0236BB10>]
```

**Comment by brianray** [comment]
please see if this problem still exists with the 0.1.3 release. If it does, first try they tests. Then make a minimal example and re-submit a ticket. Thanks for your contributions!

Also, since you are on windows please indicate if you used the installer or sources. I do not have windows, so anything you can do to help is greatly appreciated.
