### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by lantip** [brianray/mm#6]
I got that error when I'm trying to create xls. My code is something like this:

from mymodel.models import MyList
from mm.contrib.django.data_model import DjangoDataModel
from mm.contrib.django.grid import DjangoGrid
import mm

thelist = MyList.objects.filter(create_time__range=(start,end)).extra(select={
'newfield': 'select name from newtable where id=thistable.people_id'}).order_by('-create_time')

mm_doc = mm.Document(thelist, data_model_class=DjangoDataModel, grid_class=DjangoGrid)
mm_doc.write('example.xls')

I'm using Django 1.4

The same thing happen when I iterate the queryset and build the list of dict manually.

**Comment by brianray** [comment]
I wish I could see the whole traceback. Can you give me your model for MyList?

**Comment by brianray** [comment]
please see if this problem still exists with the 0.1.3 release. If it does, first try they tests. Then make a minimal example and re-submit a ticket. Thanks for your contributions!

**Comment by SachaMPS** [comment]
Traceback:
ERROR:django.request:Internal Server Error: /admin/contact/orderitem/
Traceback (most recent call last):
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 366, in wrapper
    return self.admin_site.admin_view(view)(_args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 196, in inner
    return view(request, _args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(_args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, _args2, *_kwargs2)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1153, in changelist_view
    response = self.response_action(request, queryset=cl.get_query_set(request))
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 908, in response_action
    response = func(self, request, queryset)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/stadtwerke_stuttgart_project/apps/contact/admin.py", line 63, in export_as_xls
    data = xlsDoc.writestr()
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/document_writers.py", line 21, in writestr
    return self.composer.run(child=child)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/composer_xls.py", line 220, in run
    self.iterate_grid()
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/composer_base.py", line 26, in iterate_grid
    self.write_cell(self.row_id, self.col_id, cell)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/composer_xls.py", line 165, in write_cell
    self.done_write_cell(row_id, col_id, cell, value, style)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/composer_xls.py", line 176, in done_write_cell
    new_width = get_string_width_from_style(value, style)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/composer_xls.py", line 19, in get_string_width_from_style
    return int(get_string_width(font_name, point_size, char_string) \* 50)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/lib/font_data/decorators.py", line 21, in __call__
    value = self.func(*args)
  File "/Users/smps/Sites/mllrsohn.dev/python/stadtwerke_stuttgart/env/lib/python2.7/site-packages/mm/lib/font_data/core.py", line 49, in get_string_width
    str_length = len(char_string)
TypeError: object of type 'int' has no len()

**Comment by brianray** [comment]
fixed in #11
